# Generated by Django 3.0.5 on 2020-11-18 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('education', models.CharField(max_length=20, null=True)),
                ('ethnicity', models.CharField(max_length=50, null=True)),
                ('pol_interest', models.IntegerField(null=True)),
                ('pol_stance', models.IntegerField(null=True)),
                ('md_fox', models.IntegerField(null=True)),
                ('md_cnn', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('infoString', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isAgree', models.BooleanField(default=True)),
                ('survey_id', models.IntegerField(null=True)),
                ('echo1', models.IntegerField(null=True)),
                ('echo2', models.IntegerField(null=True)),
                ('echo3', models.IntegerField(null=True)),
                ('echo4', models.IntegerField(null=True)),
                ('echo5', models.IntegerField(null=True)),
                ('real_news1_reliability', models.IntegerField(null=True)),
                ('real_news1_confidence', models.IntegerField(null=True)),
                ('real_news2_reliability', models.IntegerField(null=True)),
                ('real_news2_confidence', models.IntegerField(null=True)),
                ('real_news3_reliability', models.IntegerField(null=True)),
                ('real_news3_confidence', models.IntegerField(null=True)),
                ('fake_news1_reliability', models.IntegerField(null=True)),
                ('fake_news1_confidence', models.IntegerField(null=True)),
                ('fake_news2_reliability', models.IntegerField(null=True)),
                ('fake_news2_confidence', models.IntegerField(null=True)),
                ('fake_news3_reliability', models.IntegerField(null=True)),
                ('fake_news3_confidence', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PreSurvey',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isAgree', models.BooleanField(default=True)),
                ('survey_id', models.IntegerField(null=True)),
                ('echo1', models.IntegerField(null=True)),
                ('echo2', models.IntegerField(null=True)),
                ('echo3', models.IntegerField(null=True)),
                ('echo4', models.IntegerField(null=True)),
                ('echo5', models.IntegerField(null=True)),
                ('real_news1_reliability', models.IntegerField(null=True)),
                ('real_news1_confidence', models.IntegerField(null=True)),
                ('real_news2_reliability', models.IntegerField(null=True)),
                ('real_news2_confidence', models.IntegerField(null=True)),
                ('real_news3_reliability', models.IntegerField(null=True)),
                ('real_news3_confidence', models.IntegerField(null=True)),
                ('fake_news1_reliability', models.IntegerField(null=True)),
                ('fake_news1_confidence', models.IntegerField(null=True)),
                ('fake_news2_reliability', models.IntegerField(null=True)),
                ('fake_news2_confidence', models.IntegerField(null=True)),
                ('fake_news3_reliability', models.IntegerField(null=True)),
                ('fake_news3_confidence', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SelectTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('infoString', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalUserEnd', models.IntegerField()),
                ('totalAgreeEnd', models.IntegerField()),
                ('totalDisAgreeEnd', models.IntegerField()),
            ],
        ),
    ]
