# Generated by Django 4.0.1 on 2022-09-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presurvey',
            name='fake_news4_confidence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='fake_news4_reliability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='fake_news5_confidence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='fake_news5_reliability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='fake_news6_confidence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='fake_news6_reliability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='real_news4_confidence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='real_news4_reliability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='real_news5_confidence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='real_news5_reliability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='real_news6_confidence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='real_news6_reliability',
            field=models.IntegerField(null=True),
        ),
    ]
