# Generated by Django 4.0.1 on 2022-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_postsurvey_fake_news4_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSurvey',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
            ],
        ),
    ]
