# Generated by Django 4.0.1 on 2022-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_feedbacksurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksurvey',
            name='id',
            field=models.AutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacksurvey',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
