# Generated by Django 4.0.1 on 2022-11-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_feedbacksurvey_id_alter_feedbacksurvey_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackNewsSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('feedback_text', models.TextField()),
            ],
        ),
    ]
